USE [C:\USERS\RAPHAEL MULLER\SOURCE\REPOS\WEBATIVIDADEENTREVISTA\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

/****** Objeto: SqlProcedure [dbo].[FI_SP_PesqBeneficiario] Data do Script: 17/08/2024 15:19:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[FI_SP_PesqBeneficiario] 
@idCliente BIGINT 
AS
BEGIN
	SELECT ID,IDCLIENTE,NOME,CPF FROM BENEFICIARIOS WHERE BENEFICIARIOS.IDCLIENTE=@idCliente
END
