CREATE PROCEDURE [dbo].[FI_SP_IncBeneficiario]
	@NOME VARCHAR(100),
	@CPF VARCHAR(11),
	@IDCLIENTE BIGINT
AS
BEGIN
	INSERT INTO [dbo].[BENEFICIARIOS] (NOME, CPF, IDCLIENTE)
	VALUES (@NOME, @CPF, @IDCLIENTE)
END 
